### ISSUE TITLE
Definition of approval / consensus of Steering Council

### ISSUE THREAD

**Issue by jgrethe** [BioSchemas/governance#3]
Specifics are given at the end of the document for what is required for change of governance.  However, I didn't find (could have missed it) specific for what approval of Steering Council is.  As an example, if there are 4 members - is approval 2 (including Chair) or are 3 votes required?

This would probably be added in the Steering Council section.

**Comment by AlasdairGray** [comment]
Relevant text from the end of the [Changing the Governance Documents](https://github.com/BioSchemas/governance/blob/1.0-RFC/governance.md#changing-the-governance-documents) section
> A minimum of 80% of the Steering Council must vote and at least 2/3 of the votes must be positive to carry out the proposed action (fractions of a vote rounded up to the nearest integer). In exceptional circumstances the Steering Council Chair has authority to act alone in accepting or rejecting changes or overriding Steering Council decisions.

Following this for your specific example, it would require 3 votes from the 4 members present in the meeting (assuming that is at least 80% of the Steering Council). However, the Chair does have the authority to override that and accept the changes although this would only be done in exceptional circumstances.

If this addresses your comment then please close the issue, otherwise please indicate what changes you think need to be made.

**Comment by jgrethe** [comment]
@AlasdairGray This is specifically in the "Changing Governance" section and I assume would apply just to changing governance (as this is a super majority threshold).  I would think a similar description would be in the Steering Council section - potentially only a majority threshold.

**Comment by AlasdairGray** [comment]
Sorry, I had misread your comment originally. You are indeed correct that this is not stated. 

The intention is simple majority with the Chair having a casting vote. This would also be the case for the working groups. I'll add some text to clarify this.

**Comment by AlasdairGray** [comment]
Hopefully the changes clarify things sufficiently.
